files:
  - source: /Loop/Base.lproj/Localizable.strings
    translation: /Loop/%osx_locale%.lproj/Localizable.strings
  - source: /Loop/en.lproj/Main.strings
    translation: /Loop/%osx_locale%.lproj/Main.strings
